CREATE TABLE schedules  (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  start_at timestamp NOT NULL,
  end_at timestamp NOT NULL,
  client_id BIGSERIAL NOT NULL,
  CONSTRAINT UK_SCHEDULE_INTERVAL UNIQUE (start_at, end_at),
  CONSTRAINT UK_CLIENTS_SCHEDULES FOREIGN KEY (client_id) REFERENCES CLIENTS(id)
);